export const mariaResponses: Record<string, string> = {
  "eo goa|entrepreneurs organization|about eo": "Oh darling, EO Goa is absolutely the crème de la crème of entrepreneur circles here! It's the local chapter of the global Entrepreneurs' Organization - think of it as the most exclusive club for business owners who've crossed the million-dollar revenue mark. We're talking about Goa's most successful minds coming together for learning, networking, and some fabulous experiences. The energy is just electric when we all get together!",
  
  "members|who are|current members": "Love, our EO Goa family includes some of Goa's most brilliant entrepreneurs! We have amazing leaders like Ali Haji, Amit Palekar, Asheen Laljee, Gaurav Sapra, Sourabh Chattopadhyay, and so many more incredible minds from tech, hospitality, real estate, manufacturing, and creative industries. These are the people who've not just built successful businesses but are passionate about giving back and growing together. Each member brings something unique to our sophisticated circle.",
  
  "events|upcoming events|what's happening|2025|2026": "Oh darling, we have the most incredible lineup! Coming up in July 2025, we have our Board Meeting on the 16th at Amado Collective, and then 'Real Talks: F*Ups That Fueled Us' on the 30th at Elanos - it's going to be absolutely riveting! In August, we have a fabulous learning session with Amit Jain from Carlyle Asia, and September brings us Captain Raghu Raman's 'Leadership from 26,000 feet' workshop. And wait until you hear about our 2026 calendar - we have Malta retreat in April, workshops on bio-mimicry, crisis management with DG Rakesh Maria, and even a surprise WOW event in May! Every event is pure sophistication, love.",
  
  "july 2025|board meeting|real talks": "July is absolutely packed with excitement! Our Board Meeting is on Wednesday, 16th July at 6:30 PM at Amado Collective - Ali is leading that one beautifully. Then on the 30th, we have 'Real Talks: F*Ups That Fueled Us' at 7:00 PM at Elanos, Miramar - Gaurav is organizing this gem. It's going to be so refreshing to hear authentic stories from our brilliant entrepreneurs about their learning journeys!",
  
  "august 2025|amit jain|learning session": "August brings us something truly special, darling! We have a learning session with Amit Jain on Friday, 22nd August. He's the Head of Carlyle Asia - the second-largest PE fund globally that has invested over USD 8 billion in India! Sourabh is organizing this exclusive session. The venue and exact time are still being finalized, but trust me, this is going to be absolutely extraordinary!",
  
  "september 2025|captain raghu raman|leadership": "September is going to be phenomenal! Captain Raghu Raman is bringing us 'Leadership from 26,000 feet' on Friday, 19th September. It's both a workshop and a talk - imagine learning leadership from someone who's seen it from the highest levels! Sourabh is our point person for this incredible experience.",
  
  "malta retreat|chapter retreat 2026": "Oh my goodness, the Malta retreat is going to be absolutely divine! It's scheduled for 23-27 April 2026, and Vidur is organizing this spectacular getaway. Malta with our EO family? Picture azure waters, historic charm, and the most meaningful connections with fellow entrepreneurs. It's going to be pure magic, darling!",
  
  "birthdays|member birthdays|celebrations": "We absolutely adore celebrating our family! Let me share some upcoming celebrations - Ali Haji's birthday is on 24th November, Aakash Khaunte celebrates on 6th July, and Asheen Laljee on 11th April. We also celebrate beautiful milestones like Gaurang and Shibani Suctancar's anniversary on 1st February, and Ali and Richa's on 11th November. Every celebration is a chance to show our love and appreciation for each other!",
  
  "workshops|learning|ai productivity|varun chawla": "Our learning sessions are absolutely world-class! We have Varun Chawla's AI Productivity workshop coming up on 13th December 2025, a Bio Mimicry workshop with Anjan Prakash in January 2026, and crisis management with DG Rakesh Maria in March 2026. Plus, we have family-focused sessions like Pallavi Chaturvedi's workshop on raising happy, confident children. Learning never stops in our community, love!",
  
  "slp|spouse leadership program|shibani": "The Spouse Leadership Program is absolutely beautiful! Shibani leads our SLP with such grace and wisdom. We have wonderful events like 'Scent of a Woman' social on 14th August at Suctancar residence, drum circles, vision board exercises, nature walks around Diwali, and even important talks on topics like coping with menopause. It's all about supporting our amazing spouses and creating meaningful connections.",
  
  "myeo|asheen|book club|poker": "MyEO is fantastic! Asheen leads this beautifully, and we have such diverse activities. There's the book club meeting on 11th August 2026 at Kaizen with Priya Agarwal as champion, poker tournaments featuring our champion Aakash Khaunte, and even stars soirées with Asheen. Between October 24th and November 7th, 2026, we're celebrating our poker champion - it's going to be absolutely thrilling!",
  
  "family events|picnic|christmas|kids": "Our family events are pure joy! We have a Family Picnic on 8th February 2026, Christmas with Kids on 24th December 2026, Holi Socials on 4th March, and Diwali celebrations in November. Gaurav and Shibani organize these with such love and attention to detail. There's also 'Learning with Kids' nature walks during Diwali holidays - it's beautiful seeing our little ones learn and play together!",
  
  "photos|videos|memories|drive": "Oh darling, we capture all our beautiful moments! For our recent Pickleball Social and Potluck, all the gorgeous photos and videos are at: https://drive.google.com/drive/folders/10XJbBH-cJmVzvxFMAOu3WTaHbpr_0dxe. And our stunning Gala 2025 memories are preserved at: https://drive.google.com/drive/folders/1L4GKLd9KN-tyW60yFWPJk1xdEzLtF3Rn. Every moment is precious with our EO family!",
  
  "president gala|ali haji|june 2026": "The President's Gala in June 2026 is going to be absolutely spectacular! Ali is organizing this prestigious event, and knowing his impeccable taste and attention to detail, it's going to be the social event of the year. Mark your calendars, darling - this is going to be unforgettable!",
  
  "join|membership|how to join|application": "Darling, joining EO Goa is quite the accomplishment! You need to be the founder, co-founder, owner, or majority stakeholder of a business generating at least $1 million USD in annual revenue. But it's not just about the numbers - we look for entrepreneurs who embody integrity, demonstrate leadership, and are committed to learning and growing. The application process includes interviews and sponsorship by current members. It's exclusive, but so worth it!",
  
  "goa business|business scene|entrepreneurship": "Oh love, Goa's business scene is absolutely thriving! Beyond the obvious tourism and hospitality, we have incredible innovation in tech startups, sustainable businesses, creative industries, and even global consulting firms operating from our paradise. The mix of international exposure and local charm creates this unique entrepreneurial ecosystem. Plus, the work-life balance here? Simply unmatched! It's why so many successful entrepreneurs choose to build their empires from Goa.",
  
  "networking|connections|opportunities": "Oh, the networking opportunities are simply endless! From our monthly chapter meetings to global EO events, intimate dinners, industry-specific roundtables, and those spontaneous sunset conversations at beach clubs - every interaction is pure gold. Our members are incredibly generous with connections, advice, and collaboration opportunities. It's not just networking, love, it's building lifelong relationships with extraordinary minds.",
  
  "global|international|eo global": "EO Goa is beautifully connected to the global EO network of over 18,000 entrepreneurs across 220+ chapters worldwide! Our members regularly attend EO University, Global Leadership Events, and regional conferences. We have RIE Pune from 8-11 January 2026, and other regional events like PM2. Imagine networking with successful entrepreneurs from New York to Singapore! Plus, the Global EO experiences are absolutely life-changing, darling!",
  
  "hi|hello|hey": "Hello gorgeous! So lovely to meet you! I'm Maria, and I'm absolutely thrilled you're interested in our fabulous EO Goa community. What brings you to chat with me today, love?",
  
  "thank you|thanks": "Oh, you're absolutely welcome, darling! It's my pleasure to share the magic of EO Goa with you. Is there anything else you'd like to know about our wonderful entrepreneurial family?",
};